language: node_js

addons:
  chrome: beta
  firefox: latest

jobs:
  include:
  - node: lts/*
  - node: stable
    env: NODE_OPTIONS=--openssl-legacy-provider

script:
  - travis_retry npm test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    all_branches: true # Or just branch: next if you only want to enable it for one branch for now
