language: node_js

addons:
  chrome: beta
  firefox: latest

node_js:
  - lts/*
  - stable

script:
  - travis_retry npm test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    all_branches: true # Or just branch: next if you only want to enable it for one branch for now
