import { collapseImgixParams } from "../../src/HOFs/propFormatter"

describe('collapseImgixParams()', () => {

  it("should shorten params keys", () => {
    // TODO(luis): break these up into individual tests?
    const params = {
      brightness: undefined,
      contrast: undefined,
      exposure: undefined,
      gamma: undefined,
      highlights: undefined,
      hue: undefined,
      invert: undefined,
      saturation: undefined,
      shaddows: undefined,
      shadows: undefined,
      sharpness: undefined,
      "unsharp-mask": undefined,
      "unsharp-radius": undefined,
      vibrance: undefined,
      "auto-features": undefined,
      "background-color": undefined,
      blend: undefined,
      "blend-mode": undefined,
      "blend-align": undefined,
      "blend-alpha": undefined,
      "blend-padding": undefined,
      "blend-width": undefined,
      "blend-height": undefined,
      "blend-fit": undefined,
      "blend-crop": undefined,
      "blend-size": undefined,
      "blend-x": undefined,
      "blend-y": undefined,
      border: undefined,
      padding: undefined,
      "face-index": undefined,
      "face-padding": undefined,
      faces: undefined,
      "chroma-subsampling": undefined,
      "color-quantization": undefined,
      download: undefined,
      DPI: undefined,
      format: undefined,
      "lossless-compression": undefined,
      quality: undefined,
      "mask-image": undefined,
      "noise-blur": undefined,
      "noise-sharpen": undefined,
      "flip-direction": undefined,
      orientation: undefined,
      "rotation-angle": undefined,
      "crop-mode": undefined,
      "fit-mode": undefined,
      "image-height": undefined,
      "image-width": undefined,
      blurring: undefined,
      halftone: undefined,
      monotone: undefined,
      pixelate: undefined,
      "sepia-tone": undefined,
      height: undefined,
      width: undefined,
    }
    const expected = {
      "bri": undefined,
      "con": undefined,
      "exp": undefined,
      "gam": undefined,
      "high": undefined,
      "hue": undefined,
      "invert": undefined,
      "sat": undefined,
      "shad": undefined,
      "sharp": undefined,
      "usm": undefined,
      "usmrad": undefined,
      "vib": undefined,
       "auto": undefined,
      "bg": undefined,
      "blend": undefined,
      "bm": undefined,
      "ba": undefined,
      "balph": undefined,
      "bp": undefined,
      "bw": undefined,
      "bh": undefined,
      "bf": undefined,
      "bc": undefined,
      "bs": undefined,
      "bx": undefined,
      "by": undefined,
      "border": undefined,
      "pad": undefined,
      "faceindex": undefined,
      "facepad": undefined,
      "faces": undefined,
      "chromasub": undefined,
      "colorquant": undefined,
      "dl": undefined,
      "dpi": undefined,
      "fm": undefined,
      "lossless": undefined,
      "q": undefined,
      "mask": undefined,
      "nr": undefined,
      "nrs": undefined,
      "flip": undefined,
      "or": undefined,
      "rot": undefined,
      "crop": undefined,
      "fit": undefined,
      "h": undefined,
      "w": undefined,
      "blur": undefined,
      "htn": undefined,
      "mono": undefined,
      "px": undefined,
      "sepia": undefined,
      "h": undefined,
      "w": undefined,
    }

    const result = collapseImgixParams(params)
    expect(result).toEqual(expected)
  })
  
})
